version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart:
        on-failure:5

  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.102
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart:
      on-failure:5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
